# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh
  - name: utils
    before: |
      sudo apt-get install tree
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh
  - name: Setup Environment
    init: |
      sudo apt-get update
      sudo apt-get install -y tree