#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "there needs to be a bucket name  eg. ./bucket my-bucket-name"
  exit 1
fi

BUCKET_NAME=$1

#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="locationConstraint=ca-central-1"

